### ISSUE TITLE
Translation into spanish

### ISSUE THREAD

**Issue by chemacortes** [klen/pomodoro-tracker-locales#1]
Hi,

Attaching files of my translation into spanish (ES) of "pomodoro-tracker".
I am delighted to be useful.

Many thanks for pomodor-tracker,
-- Chema

[messages.po.txt](https://github.com/klen/pomodoro-tracker-locales/files/238570/messages.po.txt)
[static.po.txt](https://github.com/klen/pomodoro-tracker-locales/files/238569/static.po.txt)

**Comment by klen** [comment]
Oh, thank you! Just missed it, but will add Spanish soon!

**Comment by klen** [comment]
Thank you again. The locale has added and pomodoro-tracker has been updated.

**Comment by chemacortes** [comment]
OK. It's working fine. Thanks!
