### ISSUE TITLE
Czech translation

### ISSUE THREAD

**Issue by jiri-altman** [klen/pomodoro-tracker-locales#15]
I'm from Czech Republic and I use pomodoro-tracker in a daily basis, so I'm interested in translating it to my language so it can be more popular here (and also as a way of compensating the project for its importance in my routine).

**Comment by klen** [comment]
Sounds great! Here you can find the czech locale: https://github.com/klen/pomodoro-tracker-locales/tree/master/cs/LC_MESSAGES

Looking forward to see chezh language in the service!
