### ISSUE TITLE
Translation done, what next?

### ISSUE THREAD

**Issue by AntoniusGolly** [klen/pomodoro-tracker-locales#19]
I translated to German. Please consider these files. I found typos in the original English text parts but did not correct them, to avoid breaking the parsing of the language blocks.

**Comment by klen** [comment]
Hello @AntoniusGolly,

Sorry for the last reply. But where can I find the translation? BTW German locale was added to the project. It's not complete yet. Feel free to check and fix if you would like.

**Comment by AntoniusGolly** [comment]
I created a translation (within the branch "German_locale") a month ago which I still can't push to origin. I think you need to make me a collaborator.
