### ISSUE TITLE
Can I add Dutch translations?

### ISSUE THREAD

**Issue by joranvar** [klen/pomodoro-tracker-locales#37]
I already have a branch ready (https://github.com/klen/pomodoro-tracker-locales/compare/master...joranvar:add-dutch-translations?expand=1), I can make the PR whenever you want.

**Comment by klen** [comment]
@joranvar Sure, It will be great!

**Comment by klen** [comment]
@joranvar I'll merge and publish it ASAP

**Comment by klen** [comment]
@joranvar Web version has been updated. App Store version will be updated soon.

**Comment by joranvar** [comment]
Thanks very much for your work!
