### ISSUE TITLE
Turkish Translation

### ISSUE THREAD

**Issue by ertseyhan** [klen/pomodoro-tracker-locales#4]
Greetings,

I've completely translated this project into Turkish and attached files below.

Regards.

[messages.po.txt](https://github.com/klen/pomodoro-tracker-locales/files/506225/messages.po.txt)
[static.po.txt](https://github.com/klen/pomodoro-tracker-locales/files/506226/static.po.txt)

**Comment by klen** [comment]
Done, thank you!
