### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by dabalroman** [klen/pomodoro-tracker-locales#42]
Hi, I'd like to make polish translation of the project.
I'm from Poland, polish is mine native language.
Before I begin, any hints or tips?

**Comment by klen** [comment]
Sorry for delay, I didn't see the issue. I've added Polish locale here: https://github.com/klen/pomodoro-tracker-locales/blob/master/pl/LC_MESSAGES/messages.po feel free to edit it.

**Comment by klen** [comment]
The site has been updated.
