### ISSUE TITLE
Polish plural-forms

### ISSUE THREAD

**Issue by dabalroman** [klen/pomodoro-tracker-locales#52]
There is problem with plural forms in polish translation. These doesn't work at all.
The problem is that this code never worked as expected. 
Mentioned code works as expected in standard js console.

Until recently code for plural forms looked like this: 
```json
"Plural-Forms: "nplurals = 3;"
	"nmod = n%10;"
	"aForm = (n == 1);"
	"bForm = (nmod >= 2 && nmod <= 4);"
	"bFormException = (n >= 5 && n <= 21);"
	"/* cForm = (nmod >= 5 || nmod <= 1); */"
	"plural = (aForm ? 0 : bForm && !bFormException ? 1 : 2)\n"
```

Now we have:
```json
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
```
(fefe5898a5551ba1efaf2368297bdb695f880e0b)

And all of the msgstr[2] translations are gone.
Why @klen ?
Any ideas why it isn't working in pomodoro-tracker app?

**Comment by klen** [comment]
@dabalroman Looks like I lose the changes when locales' regeneration.

Going to fix.
