### ISSUE TITLE
Ukrainian

### ISSUE THREAD

**Issue by mdorotc** [klen/pomodoro-tracker-locales#53]
Hello, how to start tanslating for your pomodoro-timer to ukrainian language ?

**Comment by klen** [comment]
@mdorotc Good Day Sir,

I was on a vacation and missed your message. It's great news. I'd very like to add Ukrainian locale to the service.

You are able to edit the file here: https://github.com/klen/pomodoro-tracker-locales/blob/master/uk/LC_MESSAGES/messages.po

You can use Russian locale as a reference: https://github.com/klen/pomodoro-tracker-locales/blob/master/ru/LC_MESSAGES/messages.po

**Comment by klen** [comment]
Closing the issue because Ukranian locale has been added. Thanks @Serganth

**Comment by mdorotc** [comment]
Thank you !

пт, 18 жовт. 2019 о 15:39 Kirill Klenov <notifications@github.com> пише:
