### ISSUE TITLE
I want to add Korean for Pomodoro Tracker

### ISSUE THREAD

**Issue by naxxster** [klen/pomodoro-tracker-locales#72]
I want to add Korean for Pomodoro Tracker.
Please give help materials for it (if there is any).

**Comment by dabalroman** [comment]
If there's no Korean translation already, @klen will create directory for it.

Meanwhile, you could clone repo, copy already translated file from another language and translate every string inside to Korean. 
Unfortunately there is no way to check how your translation would look in pomodoro app until @klen pushes it to production. 

There's no any instructions about how to translate files, just look up any already done language file.

**Comment by naxxster** [comment]
Okay, I already forked the repository.
I will make translated file as you mentioned, and make a pull request after finishing it.

**Comment by klen** [comment]
@naxxster Thank you! The locale has been released: https://pomodoro-tracker.com?lang=ko

Please check
